name: beelpaq
description: A fast and secure mobile app for seamless bill payments.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  logger: ^1.3.0
  google_fonts: ^4.0.4
  go_router: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint:
  custom_lint:
  build_runner:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
